[package]
name = "indices"
description = "Zero allocation macros and methods for retrieving multiple mutable indices from a mutable slice safely"
version = "0.3.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/mcmah309/indices"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
trybuild = "^1.0.91"