[package]
name = "indices"
description = "Macro for extracting mutiple mutable indices from a slice safely"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/mcmah309/indices"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error_set = "^0.3.2"

[dev-dependencies]
trybuild = "^1.0.91"